//! Cross-reference tests against ultrahdr-core v0.2.0 golden data.
//!
//! Golden data generated from ultrahdr-core (Google libultrahdr-compatible Rust impl)
//! using the `linear-srgb` crate for transfer functions (rational polynomial, <1 ULP).
//!
//! These values are the source of truth. If gainforge disagrees with them,
//! gainforge has the bug (or a deliberate design difference that should be documented).
//!
//! Generated by: ultrahdr-core/examples/gen_golden.rs

use gainforge::TransferFunction;

// ============================================================================
// Transfer function golden data from ultrahdr-core (via linear-srgb crate)
// ============================================================================

/// sRGB EOTF (linearize): via linear-srgb crate (rational polynomial, <1 ULP)
const ULTRAHDR_SRGB_EOTF: &[(f32, f32)] = &[
    (0.00000, 0.00000000),
    (0.01000, 0.00077399),
    (0.04045, 0.00313157),
    (0.05000, 0.00393681),
    (0.10000, 0.01002424),
    (0.18000, 0.02721411),
    (0.25000, 0.05087915),
    (0.50000, 0.21404591),
    (0.75000, 0.52252531),
    (0.90000, 0.78741449),
    (1.00000, 1.00000000),
];

/// sRGB OETF (gamma): via linear-srgb crate
const ULTRAHDR_SRGB_OETF: &[(f32, f32)] = &[
    (0.0000000, 0.00000000),
    (0.0010000, 0.01292000),
    (0.0031308, 0.04044015),
    (0.0100000, 0.09984365),
    (0.0500000, 0.24779294),
    (0.1800000, 0.46135071),
    (0.2500000, 0.53709418),
    (0.5000000, 0.73535407),
    (0.7500000, 0.88082391),
    (1.0000000, 1.00000000),
];

/// PQ EOTF: SMPTE ST 2084, output 0..1 (1.0 = 10000 nits)
const ULTRAHDR_PQ_EOTF: &[(f32, f32)] = &[
    (0.00000, 0.0000000000),
    (0.01000, 0.0000002310),
    (0.04045, 0.0000037426),
    (0.05000, 0.0000060002),
    (0.10000, 0.0000324565),
    (0.18000, 0.0001738578),
    (0.25000, 0.0005154184),
    (0.50000, 0.0092245769),
    (0.75000, 0.0983377323),
    (0.90000, 0.3905634284),
    (1.00000, 0.9999963641),
];

/// PQ OETF: linear [0,1] to PQ encoded [0,1]
const ULTRAHDR_PQ_OETF: &[(f32, f32)] = &[
    (0.0000, 0.00000000),
    (0.0001, 0.14994641),
    (0.0010, 0.29969919),
    (0.0100, 0.50807846),
    (0.0500, 0.67658478),
    (0.1000, 0.75182700),
    (0.5000, 0.92654669),
    (1.0000, 0.99999988),
];

/// HLG OETF: scene linear to HLG encoded (ARIB STD-B67)
const ULTRAHDR_HLG_OETF: &[(f32, f32)] = &[
    (0.00000000, 0.00000000),
    (0.01000000, 0.17320508),
    (0.05000000, 0.38729835),
    (0.10000000, 0.54408962),
    (0.08333334, 0.50000000),
    (0.25000000, 0.73854923),
    (0.50000000, 0.87164319),
    (0.75000000, 0.94709837),
    (1.00000000, 0.99999976),
];

// ============================================================================
// sRGB cross-validation
// ============================================================================

#[test]
fn srgb_linearize_vs_ultrahdr() {
    let tf = TransferFunction::Srgb;
    for &(input, expected) in ULTRAHDR_SRGB_EOTF {
        let actual = tf.linearize(input, 1.0);
        let diff = (actual - expected).abs();
        assert!(
            diff < 0.005,
            "sRGB linearize({input}): gainforge={actual:.8}, ultrahdr={expected:.8}, diff={diff:.6}"
        );
    }
}

#[test]
fn srgb_gamma_vs_ultrahdr() {
    let tf = TransferFunction::Srgb;
    for &(input, expected) in ULTRAHDR_SRGB_OETF {
        let actual = tf.gamma(input);
        let diff = (actual - expected).abs();
        assert!(
            diff < 0.005,
            "sRGB gamma({input}): gainforge={actual:.8}, ultrahdr={expected:.8}, diff={diff:.6}"
        );
    }
}

// ============================================================================
// PQ cross-validation
//
// gainforge uses pxfm fast-math for PQ; ultrahdr-core uses linear-srgb
// rational polynomials. We expect larger divergence here.
// ============================================================================

#[test]
fn pq_linearize_shape_vs_ultrahdr() {
    let tf = TransferFunction::PerceptualQuantizer;
    // PQ EOTF values from ultrahdr-core. gainforge's PQ may have different
    // reference_display scaling, so we check relative shape rather than exact values.
    //
    // Key property: PQ is extremely nonlinear. 0.5 encoded = 0.0092 linear.
    // At 0.75 encoded = 0.098 linear. At 0.9 = 0.39 linear.
    let pq_half = tf.linearize(0.5, 1.0);
    let pq_075 = tf.linearize(0.75, 1.0);
    let pq_09 = tf.linearize(0.9, 1.0);

    // Shape checks: the ratio between these should be similar regardless of scaling
    // ultrahdr: 0.098/0.0092 ≈ 10.7x, 0.39/0.098 ≈ 3.97x
    if pq_half > 0.0 {
        let ratio_075_05 = pq_075 / pq_half;
        assert!(
            ratio_075_05 > 5.0 && ratio_075_05 < 20.0,
            "PQ shape: 0.75/0.5 ratio = {ratio_075_05:.1}, expected ~10.7"
        );
        let ratio_09_075 = pq_09 / pq_075;
        assert!(
            ratio_09_075 > 2.0 && ratio_09_075 < 8.0,
            "PQ shape: 0.9/0.75 ratio = {ratio_09_075:.1}, expected ~3.97"
        );
    }
}

#[test]
fn pq_endpoints_vs_ultrahdr() {
    let tf = TransferFunction::PerceptualQuantizer;
    // PQ EOTF(0) = 0
    let pq_zero = tf.linearize(0.0, 1.0);
    assert!(pq_zero.abs() < 0.001, "PQ linearize(0) should be ~0: {pq_zero}");

    // PQ EOTF(1.0) ≈ 1.0 (10000/10000 nits)
    // ultrahdr: 0.9999963641
    let pq_one = tf.linearize(1.0, 1.0);
    // Allow wide tolerance due to possible reference_display scaling
    assert!(pq_one > 0.5, "PQ linearize(1.0) should be high: {pq_one}");
}

// ============================================================================
// HLG cross-validation
// ============================================================================

#[test]
fn hlg_oetf_knee_point() {
    // HLG OETF has a knee at 1/12 (≈0.0833): below is sqrt, above is log.
    // ultrahdr: hlg_oetf(1/12) = 0.5 exactly.
    // gainforge uses linearize/gamma which are EOTF/OETF inverses.
    // Test that gamma(linearize(x)) roundtrips for HLG at key points.
    let tf = TransferFunction::HybridLogGamma;

    // At least verify monotonicity across the knee
    let below = tf.gamma(0.05);
    let at_knee = tf.gamma(1.0 / 12.0);
    let above = tf.gamma(0.15);

    assert!(
        below < at_knee && at_knee < above,
        "HLG gamma should be monotonic across knee: {below} < {at_knee} < {above}"
    );
}

// ============================================================================
// GainMap LUT cross-validation
// ============================================================================

/// GainMapLut from ultrahdr-core: min_boost=1, max_boost=4, gamma=1, weight=0.5
/// byte → gain factor (channel 0)
const ULTRAHDR_GAIN_LUT_W05: &[(u8, f32)] = &[
    (0, 1.00000000),
    (1, 1.00272191),
    (16, 1.04445124),
    (32, 1.09087837),
    (64, 1.19001555),
    (128, 1.41613698),
    (192, 1.68522489),
    (224, 1.83837545),
    (255, 2.00000000),
];

/// GainMapLut from ultrahdr-core: same metadata, weight=1.0 (full boost)
const ULTRAHDR_GAIN_LUT_W10: &[(u8, f32)] = &[
    (0, 1.00000000),
    (1, 1.00545120),
    (16, 1.09087837),
    (32, 1.19001555),
    (64, 1.41613698),
    (128, 2.00544405),
    (192, 2.83998299),
    (224, 3.37962413),
    (255, 4.00000000),
];

#[cfg(feature = "uhdr")]
mod gain_lut_xref {
    use super::*;
    use gainforge::{GainLUT, GainMap, make_gainmap_weight};

    fn test_metadata() -> GainMap {
        GainMap {
            max_content_boost: [4.0; 3],
            min_content_boost: [1.0; 3],
            gamma: [1.0; 3],
            offset_sdr: [0.0; 3],
            offset_hdr: [0.0; 3],
            hdr_capacity_min: 1.0,
            hdr_capacity_max: 16.0,
            use_base_cg: false,
        }
    }

    /// Compare gainforge GainLUT against ultrahdr-core GainMapLut at weight=0.5
    #[test]
    fn gain_lut_w05_vs_ultrahdr() {
        let meta = test_metadata();
        // ultrahdr-core uses 256-entry LUT indexed by byte value.
        // gainforge uses N-entry LUT indexed by float [0,1].
        // Map byte → float: byte/255.0
        let lut = GainLUT::<4096>::new(meta, 0.5);

        for &(byte, expected) in ULTRAHDR_GAIN_LUT_W05 {
            let gain = byte as f32 / 255.0;
            let actual = lut.get_gain_r_factor(gain);
            let rel_err = if expected > 0.01 {
                (actual - expected).abs() / expected
            } else {
                (actual - expected).abs()
            };
            assert!(
                rel_err < 0.03,
                "GainLUT w=0.5 byte={byte} (gain={gain:.4}): \
                 gainforge={actual:.6}, ultrahdr={expected:.6}, rel_err={rel_err:.4}"
            );
        }
    }

    /// Compare at weight=1.0 (full HDR boost)
    #[test]
    fn gain_lut_w10_vs_ultrahdr() {
        let meta = test_metadata();
        let lut = GainLUT::<4096>::new(meta, 1.0);

        for &(byte, expected) in ULTRAHDR_GAIN_LUT_W10 {
            let gain = byte as f32 / 255.0;
            let actual = lut.get_gain_r_factor(gain);
            let rel_err = if expected > 0.01 {
                (actual - expected).abs() / expected
            } else {
                (actual - expected).abs()
            };
            assert!(
                rel_err < 0.03,
                "GainLUT w=1.0 byte={byte} (gain={gain:.4}): \
                 gainforge={actual:.6}, ultrahdr={expected:.6}, rel_err={rel_err:.4}"
            );
        }
    }

    /// Verify endpoints match exactly: gain=0→min_boost, gain=1→max_boost^weight
    #[test]
    fn gain_lut_endpoints_vs_ultrahdr() {
        let meta = test_metadata();

        // weight=0.5: gain=0→1.0, gain=1→4^0.5=2.0
        let lut = GainLUT::<4096>::new(meta, 0.5);
        let at_zero = lut.get_gain_r_factor(0.0);
        let at_one = lut.get_gain_r_factor(1.0);
        assert!(
            (at_zero - 1.0).abs() < 0.01,
            "w=0.5 gain=0: {at_zero}, expected 1.0"
        );
        assert!(
            (at_one - 2.0).abs() < 0.01,
            "w=0.5 gain=1: {at_one}, expected 2.0"
        );

        // weight=1.0: gain=0→1.0, gain=1→4.0
        let lut = GainLUT::<4096>::new(meta, 1.0);
        let at_zero = lut.get_gain_r_factor(0.0);
        let at_one = lut.get_gain_r_factor(1.0);
        assert!(
            (at_zero - 1.0).abs() < 0.01,
            "w=1.0 gain=0: {at_zero}, expected 1.0"
        );
        assert!(
            (at_one - 4.0).abs() < 0.01,
            "w=1.0 gain=1: {at_one}, expected 4.0"
        );
    }
}

// ============================================================================
// Tone mapping curve cross-validation
//
// These are the RAW curve values from ultrahdr-core. gainforge's tone mappers
// operate through a u8 pipeline (linearize→tonemap→gamma→quantize), so we
// can't compare directly. But we can verify curve properties match.
// ============================================================================

/// ACES filmic from ultrahdr-core (raw f32 curve, no u8 quantization)
const ULTRAHDR_FILMIC: &[(f32, f32)] = &[
    (0.00, 0.00000000),
    (0.01, 0.00377028),
    (0.05, 0.04428307),
    (0.10, 0.12583968),
    (0.18, 0.26689893),
    (0.25, 0.37411094),
    (0.50, 0.61630690),
    (0.75, 0.73581278),
    (1.00, 0.80379742),
    (2.00, 0.91485500),
    (4.00, 0.97341704),
    (10.00, 1.00000000),
];

/// Extended Reinhard from ultrahdr-core: L_max=10.0
const ULTRAHDR_REINHARD_LMAX10: &[(f32, f32)] = &[
    (0.00, 0.00000000),
    (0.01, 0.00990198),
    (0.05, 0.04764286),
    (0.10, 0.09100000),
    (0.18, 0.15281694),
    (0.25, 0.20050001),
    (0.50, 0.33500001),
    (0.75, 0.43178573),
    (1.00, 0.50500000),
    (2.00, 0.68000001),
    (4.00, 0.83199996),
    (10.00, 1.00000000),
];

/// BT.2390 from ultrahdr-core: source=10, target=1 (includes target/source scaling)
const ULTRAHDR_BT2390_SP10_TP1: &[(f32, f32)] = &[
    (0.0, 0.00000000),
    (0.1, 0.01090000),
    (0.2, 0.02320000),
    (0.3, 0.03630000),
    (0.5, 0.06250000),
    (0.7, 0.08470000),
    (0.9, 0.09810000),
    (1.0, 0.10000000),
];

#[test]
fn tonemap_curves_documented() {
    // These aren't testable through gainforge's u8 pipeline, but we document
    // the expected values here so any future f32 API can be validated.
    //
    // Key observations from the ultrahdr-core reference:
    //
    // 1. ACES filmic at x=1.0 maps to 0.804 (not 1.0 — it's a compressive curve)
    // 2. Extended Reinhard at L_max=10 maps x=10→1.0 (exactly at L_max)
    // 3. BT.2390 source=10 target=1 maps x=1.0→0.1 (output scaled by target/source)
    //
    // If gainforge adds a raw f32 tone mapping API, test against these values.

    // Verify the golden data is internally consistent
    for &(x, y) in ULTRAHDR_FILMIC {
        assert!(!y.is_nan(), "ACES filmic NaN at {x}");
        assert!(y >= 0.0 && y <= 1.0, "ACES filmic out of range at {x}: {y}");
    }
    for &(x, y) in ULTRAHDR_REINHARD_LMAX10 {
        assert!(!y.is_nan(), "Reinhard NaN at {x}");
    }
    for &(x, y) in ULTRAHDR_BT2390_SP10_TP1 {
        assert!(!y.is_nan(), "BT.2390 NaN at {x}");
        // Output is scaled by target/source = 0.1
        assert!(y <= 0.11, "BT.2390 sp10 should be ≤0.1: {y} at {x}");
    }
}
